name: Frontend CD

on:
  push:
    branches:
      - dev  # dev 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 가져오기
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 프로젝트에 맞는 노드 버전

      # 3. 의존성 설치 및 빌드 (closzIT-front 폴더 내에서 실행)
      - name: Install and Build
        working-directory: ./closzIT-front # 해당 폴더로 이동해서 실행
        run: |
          npm ci
          npm run build
        env:
          REACT_APP_BACKEND_URL: https://api.closzit.shop
          CI: false # 경고가 에러로 간주되어 빌드가 멈추는 것 방지

      # 4. AWS 자격 증명 설정 (GitHub Secrets에 미리 등록 필요)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # 서울 리전

      # 5. 빌드 결과물을 S3에 동기화
      - name: Deploy to S3
        run: |
          aws s3 sync ./closzIT-front/build s3://closzit-frontend --delete


      # 6. CloudFront 캐시 무효화 (선택 사항)
      - name: CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths "/*" 
      ###
